In [1]:
import numpy as np, os, time, torch

In [7]:
#converting from numpy to pytorch tensor
def numpy2tensor(a):
    return torch.from_numpy(a)

print(numpy2tensor(np.array([3, 4,23, 43])))
X = np.random.randint(-1000, 1000, size=3000)
print(type(numpy2tensor(X)))

tensor([ 3,  4, 23, 43])
<class 'torch.Tensor'>


In [9]:
#converting from pytorch tensor to numpy
def tensor2numpy(a):
    return a.numpy()

a = torch.Tensor([3, 4, 5])
print(type(tensor2numpy(a)))

<class 'numpy.ndarray'>


### Vectorization - to think more mathematically

In [11]:
def PYTORCH_dot(x, y):
    return torch.dot(x, y)

np.random.seed(0)
x = np.random.randint(-1000, 1000, size=3000)
y = np.random.randint(-1000, 1000, size=3000)

X, Y = torch.from_numpy(x), torch.from_numpy(y)
print(PYTORCH_dot(X, Y))

tensor(7082791)


In [12]:
def PYTORCH_outer(x, y):
    return torch.outer(x, y)

np.random.seed(0)
X = torch.from_numpy(np.random.randint(-1000, 1000, size=2))
Y = torch.from_numpy(np.random.randint(-1000, 1000, size=3))
print(PYTORCH_outer(X, Y))

tensor([[-206348,  -68256,   52140],
        [-287973,  -95256,   72765]])


In [13]:
def PYTORCH_multiply(x, y):
    return torch.mul(x, y)

np.random.seed(0)
X = torch.from_numpy(np.random.randint(-1000, 1000, size=4))
Y = torch.from_numpy(np.random.randint(-1000, 1000, size=4))
print(PYTORCH_multiply(X, Y))

tensor([ 52140, 104517, 477343,  82728])


In [ ]:
#two vectors containing n items are pairwise multiplied and then the sum is calculated
def PYTORCH_sumproduct(x, y):
    return torch.sum(torch.outer(x, y))

np.random.seed(0)
x = torch.from_numpy(np.random.randint(-1000, 1000, size=3000))
y = torch.from_numpy(np.random.randint(-1000, 1000, size=3000))

print(PYTORCH_sumproduct(x, y))

tensor(265421520)


In [14]:
#implement ReLU (rectified linear unit) activation function, it works element wise

def PYTORCH_ReLU(x):
    return torch.where( x <= 0, 0, x)

np.random.seed(0)
X = torch.from_numpy(np.random.randint(-1000, 1000, size=(3000, 3000)))
print(PYTORCH_ReLU(X))

tensor([[  0,   0, 653,  ..., 773, 961,   0],
        [  0, 456,   0,  ..., 168, 273,   0],
        [936, 475,   0,  ..., 408,   0,   0],
        ...,
        [  0, 396, 457,  ..., 646,   0,   0],
        [645, 943,   0,  ..., 863,   0, 790],
        [641,   0, 379,  ..., 347,   0,   0]])


In [15]:
#implement prime relu (derivative of relu)
def PYTORCH_PReLU(x):
    return torch.where(x <= 0, 0, 1)

np.random.seed(0)
X = torch.from_numpy(np.random.randint(-1000, 1000, size=(3000, 3000)))
print(PYTORCH_PReLU(X))

tensor([[0, 0, 1,  ..., 1, 1, 0],
        [0, 1, 0,  ..., 1, 1, 0],
        [1, 1, 0,  ..., 1, 0, 0],
        ...,
        [0, 1, 1,  ..., 1, 0, 0],
        [1, 1, 0,  ..., 1, 0, 1],
        [1, 0, 1,  ..., 1, 0, 0]])


### Tensor manipulation

In [32]:
def PYTORCH_flatten(input_tensor):
    #flattens a 3d torch tensor to a 1d array while maintaining the order of elements
    return torch.flatten(input_tensor)

np.random.seed(0)
X = torch.from_numpy(np.random.randint(-10, 10, size=(100, 100, 100)))
t = torch.tensor([[[1, 2],
                   [3, 4]],
                  [[5, 6],
                   [7, 8]]])
print(PYTORCH_flatten(X))

tensor([  2,   5, -10,  ...,   1,   3,  -3])


In [48]:
def PYTORCH_unsqueeze(X, dim):
    #adds a new dimension to a tensor at the specified position 'dim'
    return torch.unsqueeze(X, dim)

X = torch.from_numpy(np.random.randint(0, 5, size=(100, 100)))
print(X.shape)
dim = -1
Y = torch.unsqueeze(X, dim)
print(Y.shape)   # (100, 100, 1)



torch.Size([100, 100])
torch.Size([100, 100, 1])


In [51]:
X = torch.arange(12).reshape(1, 6, 2)
print(X)

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7],
         [ 8,  9],
         [10, 11]]])


In [ ]:
#pytoch squeeze: remove the 1d part from the tensor

X = np.ranodm.randint(0, 10, size=(1, 5))


In [ ]:
import torch

x = torch.zeros(1)
print(x)

x = torch.zeros(2, 2)
print(x)

x = torch.zeros(2, 4, 4)
print(x)



tensor([0.])
tensor([[0., 0.],
        [0., 0.]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]])


In [8]:
x = torch.zeros(3, 2, 4, 4)
print(x)

tensor([[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]])


In [26]:
x = torch.randn(5, 3, 2, 2)
print(x)

flattened = x.flatten(start_dim=1)
print(flattened.shape)
print(flattened)

tensor([[[[-2.0805, -2.7033],
          [-1.6046,  1.3446]],

         [[-0.0217, -0.0256],
          [-0.8206, -0.4508]],

         [[ 1.1087,  1.3485],
          [ 1.5857,  0.1689]]],


        [[[ 1.7894,  0.2217],
          [-0.7279,  0.1108]],

         [[-0.4670, -0.2568],
          [ 1.0891,  0.2854]],

         [[-0.7712,  0.8873],
          [-1.9952,  1.2856]]],


        [[[ 0.4085,  1.0420],
          [-0.1110, -0.8652]],

         [[-0.0531,  1.4137],
          [-1.9205, -2.1909]],

         [[-0.9299, -1.5215],
          [-1.1589, -0.3033]]],


        [[[-1.2249,  0.1332],
          [-0.2071,  2.6050]],

         [[-1.1788, -0.5180],
          [-0.6712, -0.8384]],

         [[-0.8135, -1.8554],
          [ 0.1834,  0.5981]]],


        [[[ 0.8691,  1.1572],
          [-1.4452, -0.1084]],

         [[-2.0786,  0.4645],
          [ 1.2588,  0.9761]],

         [[ 0.5306, -0.0735],
          [-1.0725, -0.0864]]]])
torch.Size([5, 12])
tensor([[-2.0805, -2.7033, -1.6046,  1.34